#!/bin/sh
#
# PROVIDE: plexmon
# REQUIRE: NETWORKING plexmediaserver
# KEYWORD: shutdown

. /etc/rc.subr

name="plexmon"
rcvar="plexmon_enable"

load_rc_config $name

: ${plexmon_enable:="NO"}
: ${plexmon_user:="plex"}
: ${plexmon_group:="plex"}

logfile="/var/log/${name}.log"

command="/usr/local/bin/plexmon"
command_args="-d"

start_precmd="${name}_precmd"
extra_commands="reload"

plexmon_precmd()
{
	if [ ! -f ${logfile} ]; then
		install -m 640 -o ${plexmon_user} -g ${plexmon_group} /dev/null ${logfile}
	fi
}

run_rc_command "$1"
